### ISSUE TITLE
Hide address bar on mobile devices

### ISSUE THREAD

**Issue by end3r** [EnclaveGames/Captain-Rogers#1]
The game needs universal way to hide address (and status?) bar on mobile devices (at least iOS and Android). Asked the question at [HTML5GameDevs forums](http://www.html5gamedevs.com/topic/762-how-to-hide-address-and-status-bars-on-mobile/), got some answers, but didn't have enough skill to actually have it working.

**Comment by mar-tino** [comment]
for iOS: http://darkblue.sdf.org/weblog/ios-7-dot-1-mobile-safari-minimal-ui.html

**Comment by end3r** [comment]
Yeah, but the minimal-ui will probably be removed in iOS 8.0...
