### ISSUE TITLE
cheat score 

### ISSUE THREAD

**Issue by mar-tino** [EnclaveGames/Captain-Rogers#2]
it's easy to change game score by write in js console on pause screen, for eg: ig.game.score = 19900

**Comment by end3r** [comment]
Well, it's HTML5 with the JavaScript running on the fron-end side, so yeah, you can do that kind of thing in many games.

**Comment by mar-tino** [comment]
Closure for score variable solves the problem.

**Comment by end3r** [comment]
Yup, I'll have to do that eventually, thanks.
