### ISSUE TITLE
Styles in HTML doc

### ISSUE THREAD

**Issue by varlevi** [EnclaveGames/Captain-Rogers#4]
I would recommend moving the styles in index.html to a separate styles.css document. Adds clarity and readability and is generally considered a good practice.

**Comment by end3r** [comment]
It was done this way because the separate css file is a new request while it would contain only those three rules (html, #game, #portrait), but I don't mind doing that change. Do you want to do the Pull Request?

**Comment by varlevi** [comment]
It's up to you. I can see where your coming from in terms of the small about of rules.

**Comment by varlevi** [comment]
I'll create the pull request, but feel free not to integrate it into your project if you purfer not to have an additional file.

**Comment by varlevi** [comment]
Hmm... It's not letting me create a pull request. I don't think I have permission.

**Comment by end3r** [comment]
Go for it - can be a separate file.

That's weird, it's a public repo so you should be able to do a PR without any extra permissions.
